### ISSUE TITLE
myjenkins: Dependency errors loading some plugins

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#241]
After a fresh install of easy-jenkins I get the following

![image](https://user-images.githubusercontent.com/75182/32956760-042f78a8-cbba-11e7-9dee-059e5152a4ac.png)

**Comment by gmacario** [comment]
Fix via https://github.com/gmacario/easy-jenkins/pull/242

**Comment by lio972** [comment]
hi gmacario, do you find a solution ?

thank

**Comment by ShahanMirza** [comment]
i am facing some issue can you please share your research in this regards
