### ISSUE TITLE
Warnings have been published for the following currently installed components

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#247]
As shown on Jenkins Dashboard:

![image](https://user-images.githubusercontent.com/75182/35332864-e927ef12-010c-11e8-89c1-6b14a8aaf7a9.png)

**Comment by gmacario** [comment]
Testing PR #249 which should fix the warnings listed above

**Comment by gmacario** [comment]
Fix via PR #249

**Comment by devnagesh** [comment]
how to  fix the warnings listed above?

**Comment by gmacario** [comment]
Hi @devnagesh,

You should not find those warnings if you rebuild your docker image and create your containers from scratch

**Comment by devnagesh** [comment]
Thank you...

With Regards
Nagesh.E
8008541535

On Sun, Jul 22, 2018 at 3:58 PM, Gianpaolo Macario <notifications@github.com
