### ISSUE TITLE
"--workdir" requires API version 1.35, but the Docker daemon API version is 1.29

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#253]
Reproduced on easy-jenkins installed on build.solarma.it after doing Jenkins > Plugin Manager > Updated All plugins.

**NOTE**: The container was created a few weeks ago and never recreated from scratch

Excerpt from https://build.solarma.it/job/gm-exor-pipelines/job/master/15/console

```
Started by user Gianpaolo Macario
Obtained Jenkinsfile from 05148fddf0cb9eafdbdbb907c20c4397cbd9c70c
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/gm-exor-pipelines_master-QD4EKVNBEI6J6N543MWI5LYECZ7BEBIG7MPJJ6EYZDY2EN5AZFPQ
[Pipeline] {
[Pipeline] stage
...
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] ws
Running in /var/jenkins_home/fsl
[Pipeline] {
[Pipeline] echo
INFO: Checkout
[Pipeline] sh
[fsl] Running shell script
"--workdir" requires API version 1.35, but the Docker daemon API version is 1.29
```

**Comment by gmacario** [comment]
Trying to reproduce on itm-gmacario-w7

1. Before updating plugins ==> No message "--workdir" requires API version 1.35, but the Docker daemon API version is 1.29

http://192.168.64.205:9080/job/gm-exor-pipelines/job/master/18/console

2. Update all plugins

<img width="707" alt="schermata 2018-02-10 alle 07 41 59" src="https://user-images.githubusercontent.com/75182/36059302-faa1291c-0e35-11e8-8276-477bc056fa8e.png">

TODO

**Comment by gmacario** [comment]
Running `docker info` on build.solarma.it

```
gmacario@mv-linux-powerhorse:~ $ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 171
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 331
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67GiB
Name: mv-linux-powerhorse
ID: TEBU:YPQG:YKXN:A2H5:MBWL:VAJK:IRPJ:FP7C:BULG:MTGY:BJY7:ODWK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
gmacario@mv-linux-powerhorse:~ $
```

**Comment by gmacario** [comment]
On another Ubuntu 16.04 machine with a more recent installation:

```
gmacario@itm-gmacario-w7:~ $ dpkg -l | grep docker
ii  docker-ce                                   17.12.0~ce-0~ubuntu                          amd64        Docker: the open-source application container engine
gmacario@itm-gmacario-w7:~ $
```

**Comment by gmacario** [comment]
**CONCLUSION**: The issue is not related to easy-jenkins but instead to the version of the Docker engine installed on the host.

We should document this minimum version requirement in the project `README.md`

**Comment by maheshwabale1** [comment]
Hi @gmacario 

I have observe same is, is there any work-around to resolve this issue ? 

here is error message from jenkins pipeline : 

"--workdir" requires API version 1.35, but the Docker daemon API version is 1.27

**Comment by gmacario** [comment]
Hi @maheshwabale1,

My apologies for the late reply,

The workaround - or actually, the solution - is to update the version of Docker which is installed on the host

**Comment by rlogiacco** [comment]
What if I just can't update Docker to a higher version?

**Comment by gmacario** [comment]
Hi @rlogiacco 

> What if I just can't update Docker to a higher version?

No idea. Where are you trying to run easy-jenkins?

```shell
uname -a
cat /etc/os-release
docker --version
docker info
```

**Comment by rlogiacco** [comment]
I am on [Atomic RHEL](https://www.projectatomic.io/) and apparently, there's no update available...

**Comment by gmacario** [comment]
@rlogiacco if so you might try downgrading the version of docker installed in https://github.com/gmacario/easy-jenkins/blob/master/myjenkins/Dockerfile#L29

Unfortunately I am not aware about specific command line to do that, you should investigate an alternate command
