### ISSUE TITLE
Give a 10min demo of easy-jenkins

### ISSUE THREAD

**Issue by gmacario** [gmacario/easy-jenkins#268]
As part of the [Jenkins & Java 10+ Online Hackathon (Jun 18-22)](https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/) upon @oleg-nenashev proposal I will be giving a 10 min demo on 2018-06-22 16:00 UTC with the following contents:

1. Short easy-jenkins project Introduction 
2. Experience regarding the Java 10 hackathon

**Comment by gmacario** [comment]
Assembling demo storyboard - draft [here](https://gist.github.com/gmacario/603263d70f82aa4c2117fc991c412206)

**Comment by oleg-nenashev** [comment]
👍

**Comment by gmacario** [comment]
I gave the demo on 2018-06-22.

YouTube Video: https://www.youtube.com/watch?v=1ZX9qA0AZjM (from 18:52 to 28:10)

**Comment by gmacario** [comment]
Adding instructions via https://github.com/gmacario/easy-jenkins/commit/7f3917c7f1e45483393370ff82f72a10acf1d691

**Comment by oleg-nenashev** [comment]
Nice, thanks!
